name: MLflow CI Training

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install MLflow
        run: pip install mlflow==2.18.0

      - name: Run MLflow Project
        working-directory: MLProject
        run: |
          mlflow run . \
            -P n_estimators=${{ github.event.inputs.n_estimators || '100' }} \
            -P max_depth=${{ github.event.inputs.max_depth || '5' }} \
            -P min_samples_split=${{ github.event.inputs.min_samples_split || '2' }} \
            -P test_size=0.2